export interface Celebrity {
    name: string
    category: string
    E: number
    K: number
    B: number
    A: number
    tagline: string
    traits: string[]
}

export const celebrities: Celebrity[] = [
    // MUSIC - 30%
    { name: "Taylor Swift", category: "Musik", E: 7, K: 6, B: 7, A: 6, tagline: "Storytelling als Superkraft", traits: ["Strategisch", "Emotional intelligent", "Perfektionistisch", "Rachelustig-kreativ"] },
    { name: "Beyonc\u00e9", category: "Musik", E: 8, K: 7, B: 8, A: 7, tagline: "Excellence als Lebensform", traits: ["Diszipliniert", "Vision\u00e4r", "Kontrolliert", "Ikonisch"] },
    { name: "Billie Eilish", category: "Musik", E: 4, K: 9, B: 5, A: 8, tagline: "Leise Revolution", traits: ["Authentisch", "Introspektiv", "Nonkonform", "Sensibel"] },
    { name: "Harry Styles", category: "Musik", E: 8, K: 8, B: 8, A: 5, tagline: "Sanfte Rebellion", traits: ["Fluid", "Warmherzig", "Mutig", "Spielerisch"] },
    { name: "Doja Cat", category: "Musik", E: 9, K: 10, B: 6, A: 4, tagline: "Chaos als Kunstform", traits: ["Unberechenbar", "Genial", "Provokant", "Selbstironisch"] },
    { name: "The Weeknd", category: "Musik", E: 4, K: 8, B: 4, A: 6, tagline: "Dunkle Romantik", traits: ["Mysteri\u00f6s", "Obsessiv", "\u00c4sthetisch", "Melancholisch"] },
    { name: "Bad Bunny", category: "Musik", E: 8, K: 7, B: 7, A: 5, tagline: "Grenzenlose Energie", traits: ["Authentisch", "Kulturstolz", "Experimental", "Feierlich"] },
    { name: "Dua Lipa", category: "Musik", E: 7, K: 6, B: 6, A: 7, tagline: "Disziplinierter Glamour", traits: ["Ehrgeizig", "Elegant", "Fokussiert", "Modern"] },
    { name: "Olivia Rodrigo", category: "Musik", E: 6, K: 7, B: 6, A: 8, tagline: "Rohe Emotion", traits: ["Verletzlich", "Ehrlich", "Jung", "Intensiv"] },
    { name: "Tyler, The Creator", category: "Musik", E: 7, K: 10, B: 5, A: 3, tagline: "Genie ohne Grenzen", traits: ["Vision\u00e4r", "Exzentrisch", "Multitalent", "Kompromisslos"] },
    { name: "Rihanna", category: "Musik", E: 8, K: 7, B: 6, A: 8, tagline: "Boss-Energy", traits: ["Selbstbewusst", "Business-smart", "Mutig", "Ikone"] },
    { name: "Post Malone", category: "Musik", E: 6, K: 7, B: 8, A: 4, tagline: "Weicher Kern, harte Schale", traits: ["Bodenst\u00e4ndig", "Emotional", "Loyal", "Entspannt"] },
    { name: "SZA", category: "Musik", E: 5, K: 8, B: 5, A: 7, tagline: "Verletzliche St\u00e4rke", traits: ["Introspektiv", "Ehrlich", "Komplex", "Wachsend"] },
    { name: "Drake", category: "Musik", E: 6, K: 6, B: 7, A: 8, tagline: "Emotionaler Stratege", traits: ["Adaptiv", "Sentimental", "Kalkuliert", "Erfolgsorientiert"] },
    { name: "Ariana Grande", category: "Musik", E: 7, K: 6, B: 7, A: 6, tagline: "Resilienz mit Glamour", traits: ["Stark", "Professionell", "Emotional", "Perfektionistisch"] },
    { name: "Kendrick Lamar", category: "Musik", E: 5, K: 9, B: 5, A: 9, tagline: "Poetischer Prophet", traits: ["Tiefgr\u00fcndig", "Bewusst", "Brillant", "Introvertiert"] },
    { name: "Lady Gaga", category: "Musik", E: 8, K: 9, B: 7, A: 8, tagline: "Radikale Selbsterfindung", traits: ["Transformativ", "Mutig", "Empathisch", "Theatralisch"] },
    { name: "Ed Sheeran", category: "Musik", E: 5, K: 5, B: 8, A: 5, tagline: "Nice Guy Energy", traits: ["Bodenst\u00e4ndig", "Romantisch", "Beharrlich", "Nahbar"] },
    { name: "Lil Nas X", category: "Musik", E: 9, K: 8, B: 7, A: 6, tagline: "Provokation als Freude", traits: ["Furchtlos", "Humorvoll", "Selbstbewusst", "Kulturver\u00e4ndernd"] },
    { name: "Demi Lovato", category: "Musik", E: 7, K: 6, B: 7, A: 8, tagline: "Offene Wunden, offenes Herz", traits: ["Verletzlich", "K\u00e4mpferisch", "Ehrlich", "Resilient"] },
    { name: "Travis Scott", category: "Musik", E: 7, K: 8, B: 5, A: 6, tagline: "Sensorische \u00dcberw\u00e4ltigung", traits: ["Vision\u00e4r", "Intensiv", "Atmosph\u00e4risch", "Ehrgeizig"] },
    { name: "Miley Cyrus", category: "Musik", E: 9, K: 8, B: 6, A: 5, tagline: "St\u00e4ndige Metamorphose", traits: ["Freigeist", "Authentisch", "Rebellisch", "Experimentell"] },
    { name: "Bruno Mars", category: "Musik", E: 8, K: 7, B: 8, A: 6, tagline: "Vintage Charme", traits: ["Charismatisch", "Perfektionistisch", "Entertainer", "Nostalgisch"] },
    { name: "Cardi B", category: "Musik", E: 10, K: 7, B: 7, A: 7, tagline: "Unfiltered Queen", traits: ["Direkt", "Lustig", "Selbstgemacht", "Laut"] },
    { name: "Shawn Mendes", category: "Musik", E: 5, K: 5, B: 7, A: 6, tagline: "Sanfter Ehrgeiz", traits: ["Sensibel", "Reflektiert", "Authentisch", "K\u00e4mpfend"] },
    { name: "Rosal\u00eda", category: "Musik", E: 6, K: 9, B: 5, A: 7, tagline: "Tradition trifft Innovation", traits: ["K\u00fcnstlerisch", "Kulturell", "Avantgarde", "Mystisch"] },
    { name: "Jack Harlow", category: "Musik", E: 8, K: 6, B: 8, A: 5, tagline: "Charmanter Chaos-Agent", traits: ["Witzig", "Selbstbewusst", "Locker", "Charmant"] },
    { name: "Megan Thee Stallion", category: "Musik", E: 9, K: 7, B: 6, A: 8, tagline: "Hot Girl Energy", traits: ["Selbstbewusst", "Gebildet", "Stark", "Empowernd"] },
    { name: "David Bowie", category: "Legende", E: 6, K: 10, B: 5, A: 4, tagline: "Ewiger Wandler", traits: ["Cham\u00e4leon", "Vision\u00e4r", "Mysteri\u00f6s", "Grenzenlos"] },
    { name: "Freddie Mercury", category: "Legende", E: 10, K: 9, B: 7, A: 5, tagline: "Theatralische Ekstase", traits: ["Magnetisch", "Exzessiv", "Brillant", "Legend\u00e4r"] },
    { name: "Timoth\u00e9e Chalamet", category: "Film", E: 5, K: 8, B: 6, A: 7, tagline: "Verletzliche Intensit\u00e4t", traits: ["K\u00fcnstlerisch", "Sensibel", "Fokussiert", "Charismatisch"] },
    { name: "Zendaya", category: "Film", E: 6, K: 7, B: 7, A: 7, tagline: "M\u00fchelose Exzellenz", traits: ["Vielseitig", "Elegant", "Bodenst\u00e4ndig", "Aufsteigend"] },
    { name: "Keanu Reeves", category: "Film", E: 3, K: 5, B: 8, A: 5, tagline: "Stille G\u00fcte", traits: ["Bescheiden", "Freundlich", "Tiefgr\u00fcndig", "Loyal"] },
    { name: "Florence Pugh", category: "Film", E: 7, K: 7, B: 7, A: 7, tagline: "Furchtlose Pr\u00e4senz", traits: ["Mutig", "Authentisch", "Intensiv", "Direkt"] },
    { name: "Pedro Pascal", category: "Film", E: 7, K: 6, B: 9, A: 5, tagline: "Internet's Daddy", traits: ["Warmherzig", "Loyal", "Charmant", "Besch\u00fctzend"] },
    { name: "Sydney Sweeney", category: "Film", E: 6, K: 6, B: 6, A: 8, tagline: "Untersch\u00e4tzte Ambition", traits: ["Ehrgeizig", "Fokussiert", "Vielseitig", "\u00dcberraschend"] },
    { name: "Tom Holland", category: "Film", E: 8, K: 5, B: 8, A: 6, tagline: "Enthusiastischer Spoiler-King", traits: ["Energetisch", "Ehrlich", "Charmant", "Unschuldig"] },
    { name: "Emma Stone", category: "Film", E: 6, K: 7, B: 7, A: 6, tagline: "Witzig & Tiefgr\u00fcndig", traits: ["Selbstironisch", "Intelligent", "Nahbar", "Talentiert"] },
    { name: "Robert Pattinson", category: "Film", E: 4, K: 8, B: 4, A: 4, tagline: "Chaotisches Genie", traits: ["Exzentrisch", "Selbstironisch", "K\u00fcnstlerisch", "Unberechenbar"] },
    { name: "Margot Robbie", category: "Film", E: 7, K: 7, B: 7, A: 8, tagline: "Strategische Sch\u00f6nheit", traits: ["Smart", "Ehrgeizig", "Vielseitig", "Businessorientiert"] },
    { name: "Adam Driver", category: "Film", E: 4, K: 8, B: 5, A: 7, tagline: "Intensive Tiefe", traits: ["Fokussiert", "Unkonventionell", "Intensiv", "Diszipliniert"] },
    { name: "Ana de Armas", category: "Film", E: 6, K: 6, B: 7, A: 7, tagline: "Aufsteigende Kraft", traits: ["Charismatisch", "Fokussiert", "Elegant", "Resilient"] },
    { name: "Oscar Isaac", category: "Film", E: 6, K: 7, B: 8, A: 5, tagline: "Charmanter Intellektueller", traits: ["Vielseitig", "Gebildet", "Warm", "K\u00fcnstlerisch"] },
    { name: "Anya Taylor-Joy", category: "Film", E: 5, K: 8, B: 5, A: 7, tagline: "Au\u00dferirdische Eleganz", traits: ["Einzigartig", "Fokussiert", "Mysteri\u00f6s", "K\u00fcnstlerisch"] },
    { name: "Jacob Elordi", category: "Film", E: 5, K: 6, B: 5, A: 6, tagline: "Reluctant Heartthrob", traits: ["Zur\u00fcckhaltend", "Ehrgeizig", "K\u00fcnstlerisch", "Geheimnisvoll"] },
    { name: "Jenna Ortega", category: "Film", E: 5, K: 7, B: 6, A: 8, tagline: "Gen Z Horror Queen", traits: ["Fokussiert", "Professionell", "Kreativ", "Aufsteigend"] },
    { name: "Ryan Gosling", category: "Film", E: 5, K: 7, B: 6, A: 5, tagline: "Cooler Romantiker", traits: ["Entspannt", "Selbstironisch", "Loyal", "K\u00fcnstlerisch"] },
    { name: "Jennifer Lawrence", category: "Film", E: 8, K: 6, B: 8, A: 5, tagline: "Relatable Superstar", traits: ["Authentisch", "Lustig", "Direkt", "Bodenst\u00e4ndig"] },
    { name: "Austin Butler", category: "Film", E: 5, K: 7, B: 6, A: 8, tagline: "Method-Actor Energy", traits: ["Hingegeben", "Fokussiert", "Transformativ", "Ehrgeizig"] },
    { name: "Glen Powell", category: "Film", E: 8, K: 5, B: 8, A: 7, tagline: "All-American Charm", traits: ["Charismatisch", "Ehrgeizig", "Witzig", "Klassisch"] },
    { name: "Aubrey Plaza", category: "Film", E: 5, K: 8, B: 5, A: 4, tagline: "Deadpan Genius", traits: ["Sarkastisch", "Einzigartig", "Intelligent", "Unvorhersehbar"] },
    { name: "Barry Keoghan", category: "Film", E: 6, K: 9, B: 5, A: 7, tagline: "Unheimlich Talentiert", traits: ["Intensiv", "Unkonventionell", "Mutig", "Roh"] },
    { name: "Meryl Streep", category: "Legende", E: 5, K: 8, B: 6, A: 7, tagline: "Meisterin der Verwandlung", traits: ["Perfektionistisch", "Vielseitig", "Intelligent", "Legend\u00e4r"] },
    { name: "Leonardo DiCaprio", category: "Film", E: 6, K: 7, B: 5, A: 8, tagline: "Passionierter Perfektionist", traits: ["Engagiert", "Fokussiert", "Privat", "Ehrgeizig"] },
    { name: "Audrey Hepburn", category: "Legende", E: 4, K: 6, B: 8, A: 8, tagline: "Elegante Menschlichkeit", traits: ["Grazi\u00f6s", "Mitf\u00fchlend", "Stilvoll", "Humanit\u00e4r"] },
    { name: "Elon Musk", category: "Tech", E: 7, K: 9, B: 3, A: 4, tagline: "Chaos-Vision\u00e4r", traits: ["Unberechenbar", "Genial", "Kontrovers", "Rastlos"] },
    { name: "MrBeast", category: "Creator", E: 8, K: 8, B: 7, A: 9, tagline: "Algorithmus-Genie", traits: ["Strategisch", "Gro\u00dfz\u00fcgig", "Obsessiv", "Skalierend"] },
    { name: "Emma Chamberlain", category: "Creator", E: 6, K: 8, B: 7, A: 5, tagline: "Authentisches Chaos", traits: ["Relatable", "Trendsetting", "Ehrlich", "Kreativ"] },
    { name: "Charli D'Amelio", category: "Creator", E: 6, K: 5, B: 7, A: 6, tagline: "Accidental Icon", traits: ["Nahbar", "Anpassungsf\u00e4hig", "Bodenst\u00e4ndig", "Resilient"] },
    { name: "KSI", category: "Creator", E: 9, K: 7, B: 7, A: 8, tagline: "Multihyphenate Hustler", traits: ["Ehrgeizig", "Vielseitig", "Laut", "Resilient"] },
    { name: "Oprah Winfrey", category: "Media", E: 8, K: 6, B: 9, A: 9, tagline: "Empathie als Imperium", traits: ["Empathisch", "Weise", "Einflussreich", "Inspirierend"] },
    { name: "Mark Zuckerberg", category: "Tech", E: 4, K: 7, B: 4, A: 9, tagline: "Awkward Weltherrscher", traits: ["Fokussiert", "Analytisch", "Sozial unbeholfen", "M\u00e4chtig"] },
    { name: "Jeff Bezos", category: "Tech", E: 6, K: 6, B: 4, A: 10, tagline: "Gnadenloser Optimierer", traits: ["Kalkuliert", "Langfristig", "R\u00fccksichtslos", "Vision\u00e4r"] },
    { name: "Gary Vaynerchuk", category: "Business", E: 10, K: 6, B: 8, A: 9, tagline: "Hustle-Prediger", traits: ["Energetisch", "Motivierend", "Direkt", "Rastlos"] },
    { name: "Kylie Jenner", category: "Business", E: 7, K: 6, B: 6, A: 8, tagline: "Selbst-Marketing-Genie", traits: ["Strategisch", "Trend-aware", "Businessorientiert", "Privat"] },
    { name: "Addison Rae", category: "Creator", E: 8, K: 5, B: 7, A: 7, tagline: "Diversifizierte Influencerin", traits: ["Ehrgeizig", "Adaptiv", "Social", "Gesch\u00e4ftst\u00fcchtig"] },
    { name: "David Dobrik", category: "Creator", E: 9, K: 7, B: 8, A: 6, tagline: "Chaos-Content-K\u00f6nig", traits: ["Energetisch", "Gro\u00dfz\u00fcgig", "Unterhaltsam", "Kontrovers"] },
    { name: "Pokimane", category: "Creator", E: 6, K: 6, B: 7, A: 6, tagline: "Chill Queen", traits: ["Entspannt", "Konsistent", "Community-orientiert", "Smart"] },
    { name: "Logan Paul", category: "Creator", E: 9, K: 7, B: 6, A: 8, tagline: "Reinvention Machine", traits: ["Resilient", "Kontrovers", "Ehrgeizig", "Lernend"] },
    { name: "PewDiePie", category: "Creator", E: 6, K: 7, B: 6, A: 4, tagline: "Entspannter K\u00f6nig", traits: ["Selbstironisch", "Unabh\u00e4ngig", "Langlebig", "Authentisch"] },
    { name: "Hailey Bieber", category: "Business", E: 6, K: 6, B: 6, A: 7, tagline: "Cool Girl Entrepreneur", traits: ["Trendy", "Businessorientiert", "Selbstbewusst", "Modern"] },
    { name: "Khaby Lame", category: "Creator", E: 7, K: 7, B: 9, A: 5, tagline: "Stille Kom\u00f6die", traits: ["Einfach", "Universal", "Clever", "Bescheiden"] },
    { name: "Alexandria Ocasio-Cortez", category: "Politik", E: 8, K: 7, B: 7, A: 9, tagline: "Furchtlose Stimme", traits: ["Leidenschaftlich", "Direkt", "\u00dcberzeugend", "K\u00e4mpferisch"] },
    { name: "Steve Jobs", category: "Legende", E: 6, K: 10, B: 4, A: 9, tagline: "Reality Distortion Field", traits: ["Vision\u00e4r", "Perfektionistisch", "Kompromisslos", "Ikonisch"] },
    { name: "Bill Gates", category: "Tech", E: 5, K: 7, B: 5, A: 9, tagline: "Nerd mit Mission", traits: ["Analytisch", "Philanthropisch", "Langfristig", "Pragmatisch"] },
    { name: "Cristiano Ronaldo", category: "Sport", E: 8, K: 5, B: 6, A: 10, tagline: "Obsessive Exzellenz", traits: ["Diszipliniert", "Ehrgeizig", "Selbstverliebt", "Legend\u00e4r"] },
    { name: "Lionel Messi", category: "Sport", E: 4, K: 8, B: 7, A: 7, tagline: "Stilles Genie", traits: ["Bescheiden", "Brillant", "Loyal", "Magisch"] },
    { name: "Serena Williams", category: "Sport", E: 7, K: 6, B: 7, A: 9, tagline: "Unbeugsame K\u00f6nigin", traits: ["Dominant", "K\u00e4mpferisch", "Inspirierend", "Legend\u00e4r"] },
    { name: "LeBron James", category: "Sport", E: 8, K: 6, B: 8, A: 9, tagline: "K\u00f6nig mit Kalk\u00fcl", traits: ["Strategisch", "Leader", "Gesch\u00e4ftst\u00fcchtig", "Ehrgeizig"] },
    { name: "Simone Biles", category: "Sport", E: 6, K: 7, B: 6, A: 8, tagline: "Mentale St\u00e4rke", traits: ["Mutig", "Ehrlich", "Stark", "Bahnbrechend"] },
    { name: "Lewis Hamilton", category: "Sport", E: 7, K: 7, B: 6, A: 8, tagline: "Speed & Style", traits: ["Ehrgeizig", "Stilbewusst", "Aktivistisch", "Exzellent"] },
    { name: "Naomi Osaka", category: "Sport", E: 4, K: 6, B: 5, A: 7, tagline: "Introvertierte Power", traits: ["Sensibel", "Stark", "Authentisch", "Bahnbrechend"] },
    { name: "Tom Brady", category: "Sport", E: 6, K: 5, B: 6, A: 10, tagline: "GOAT Mentalit\u00e4t", traits: ["Diszipliniert", "Fokussiert", "Legend\u00e4r", "Obsessiv"] },
    { name: "Usain Bolt", category: "Sport", E: 9, K: 6, B: 8, A: 6, tagline: "Blitz & Lachen", traits: ["Charismatisch", "Selbstbewusst", "Unterhaltsam", "Ikonisch"] },
    { name: "Stephen Curry", category: "Sport", E: 7, K: 7, B: 8, A: 7, tagline: "Revolution mit L\u00e4cheln", traits: ["Innovativ", "Bescheiden", "Familienorientiert", "Spielver\u00e4ndernd"] },
    { name: "Shaquille O'Neal", category: "Legende", E: 10, K: 6, B: 9, A: 6, tagline: "Entertainer-Riese", traits: ["Lustig", "Gro\u00dfz\u00fcgig", "Dominant", "Lovable"] },
    { name: "Michael Jordan", category: "Legende", E: 7, K: 7, B: 4, A: 10, tagline: "Gnadenloser Gewinner", traits: ["Kompetitiv", "Legend\u00e4r", "Perfektionistisch", "Intensiv"] },
    { name: "Kylian Mbapp\u00e9", category: "Sport", E: 7, K: 7, B: 6, A: 8, tagline: "Junge Legende", traits: ["Ehrgeizig", "Schnell", "Selbstbewusst", "Aufsteigend"] },
    { name: "Rafael Nadal", category: "Sport", E: 6, K: 5, B: 7, A: 9, tagline: "Dem\u00fctiger K\u00e4mpfer", traits: ["Diszipliniert", "Bescheiden", "K\u00e4mpferisch", "Respektiert"] },
    { name: "Alex Morgan", category: "Sport", E: 7, K: 5, B: 7, A: 8, tagline: "F\u00fchrung durch Leistung", traits: ["K\u00e4mpferisch", "Vorbildlich", "Ehrgeizig", "Inspirierend"] },
    { name: "Greta Thunberg", category: "Aktivismus", E: 4, K: 6, B: 4, A: 10, tagline: "Unbequeme Wahrheit", traits: ["Kompromisslos", "Fokussiert", "Authentisch", "Unbeirrt"] },
    { name: "Malala Yousafzai", category: "Aktivismus", E: 5, K: 5, B: 7, A: 10, tagline: "St\u00e4rker als Kugeln", traits: ["Mutig", "Inspirierend", "Bescheiden", "K\u00e4mpferisch"] },
    { name: "Banksy", category: "Kunst", E: 2, K: 10, B: 3, A: 8, tagline: "Unsichtbare Revolution", traits: ["Mysteri\u00f6s", "Provokant", "Genial", "Anonym"] },
    { name: "Trevor Noah", category: "Comedy", E: 8, K: 8, B: 8, A: 6, tagline: "Humor als Br\u00fccke", traits: ["Intelligent", "Warmherzig", "Global", "Witzig"] },
    { name: "Dalai Lama", category: "Spiritualit\u00e4t", E: 7, K: 5, B: 10, A: 8, tagline: "Mitgef\u00fchl als Weg", traits: ["Weise", "Friedlich", "Humorvoll", "Inspirierend"] },
    { name: "Michelle Obama", category: "Aktivismus", E: 7, K: 6, B: 8, A: 9, tagline: "When They Go Low", traits: ["Inspirierend", "Eloquent", "Stark", "Warmherzig"] },
    { name: "Bernie Sanders", category: "Politik", E: 7, K: 5, B: 6, A: 10, tagline: "Konsistente \u00dcberzeugung", traits: ["Authentisch", "Leidenschaftlich", "Unbeirrt", "K\u00e4mpferisch"] },
    { name: "Ai Weiwei", category: "Kunst", E: 6, K: 9, B: 4, A: 9, tagline: "Kunst als Widerstand", traits: ["Mutig", "Provokant", "Vision\u00e4r", "Kompromisslos"] },
    { name: "Ruth Bader Ginsburg", category: "Legende", E: 5, K: 6, B: 6, A: 10, tagline: "Notorious RBG", traits: ["K\u00e4mpferisch", "Beharrlich", "Brillant", "Ikonisch"] },
    { name: "Jacinda Ardern", category: "Politik", E: 7, K: 6, B: 9, A: 8, tagline: "Empathie in F\u00fchrung", traits: ["Empathisch", "Entschieden", "Modern", "Inspirierend"] }
];
